### PR TITLE
Retrieve studies from transmart-rest-api

### PR DESCRIPTION
**Pull request by rnugraha**
Following features have been added:
- Login
- Retrieve studies from rest-api
- unit test for main-controller

TODO:
- connect to transmart-rest-api via oauth2
- unit test for all components
- e2e testing

### CODE REVIEW

**Comment by kretep** [comment]
For some reason, gulp serve:dist runs a version that throws a javascript error. Haven't looked into the details. Possibly some stuff got messed up in the minification.

**Comment by rnugraha** [comment]
gulp-ng-annotate lib has just updated. Should be able to run gulp serve:dist now.

**Comment by kretep** [comment]
Looks good, although the protractor tests are failing. (I guess we should be setting up the automated builds in travis?)

**Comment by rnugraha** [comment]
That's because we don't have real e2e testing defined yet. Will merge for no others critical comments. Thx!

**Comment by kretep** [comment]
Ok. These branches can now be deleted, or are you still using them?

**Pull request merged**
